services:

  api-gateway:
    image: ecommerce-api-gateway:1.0.0
    ports:
      - "8080:8080"
    environment:
      PRODUCT_SERVICE_URL: http://product-service:3001
      ORDER_SERVICE_URL: http://order-service:3002
    networks:
      - ecommerce-network
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M

  product-service:
    image: ecommerce-product-service:1.0.0
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ecommerce-network
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M

  order-service:
    image: ecommerce-order-service:1.0.1
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecommerce-network
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecommerce_user -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ecommerce-network
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M


  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ecommerce-network
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M

volumes:
  postgres_data:
  redis_data:

networks:
  ecommerce-network:
